spring:
  application:
    name: hrm-eureka
server:
  port: 7001
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/ #单机配置
